import type { Metadata } from "next";
import "./globals.css";
import { ChildProps } from "../types";
import { ThemeProvider } from "@/components/providers/theme-provider";
import {Crete_Round, Work_Sans} from 'next/font/google'



const creteRound = Crete_Round({
  weight: ['400'],
  variable: '--font-creteRound',
  subsets: ['latin']
})

const workSans = Work_Sans({
  weight: ['500', '600'],
  variable: '--font-workSans',
  subsets: ['latin']
})
// const [languageChange, setLanguageChange] = useState(
//   localStorage.getItem("language")
// );

// const toggleLanguage = (e) => {
//   e.preventDefault();
//   localStorage.setItem("language", e.target.value);
//   setLanguageChange(e.target.value);
//   // queryClient.invalidateQueries({ type: "all" });
// };


// if (!localStorage.getItem("language")) localStorage.setItem("language", "uz");

export const metadata: Metadata = {
  title: "DachaOL",
  description: "Generated by create next app",
};

function RootLayout({children}: ChildProps) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <title>Dacha Ol</title>
      </head>
      <body
        className={`antialiased ${workSans.variable} ${creteRound.variable}`}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          {/* <LanguageContext.Provider value={{languageChange, toggleLanguage}}>
          </LanguageContext.Provider> */}
            {children}
        </ThemeProvider>
      </body>
    </html>
  );
}

export default RootLayout;
