import type { Metadata } from "next";
import "./globals.css";
import { ChildProps } from "../types";
import RootLayoutClient from "@/components/providers/root-layout";


export const metadata: Metadata = {
  title: "DachaOL",
  description: "Generated by create next app",
};

function RootLayout({children}: ChildProps) {  

  return <html lang="en">
        <body>
          {/* Bu yerda klientga xos RootLayoutClient komponentini render qilamiz */}
          <RootLayoutClient>
            {children}
          </RootLayoutClient>
        </body>
      </html>
}

export default RootLayout;
